#!/usr/bin/env python3
"""The firmware of AppleWin's own that the core carries as resources, as a table.

AppleWin reaches its ROMs through FrameBase::GetResource(id, type, size): on
Windows that is FindResource over the .rc file, and the Linux frontends embed
the same files into the binary. The core embeds only what AppleWin wrote
itself; the rest is the project's firmware (waterbox.config). The numeric ids
come from upstream's own resource.h and the bytes from its tree - nothing is
copied into this repository.

usage: gen-resources.py <AppleWin checkout> <out.cpp>
"""
import os
import re
import sys

# resource id -> file under resource/ (or firmware/), as Applewin.rc has them
RESOURCES = [
    # only what AppleWin wrote itself: the hard-disk controller firmware
    # (firmware/HDD, GPL with the rest of AppleWin). Apple's ROMs, the clones'
    # and the card firmware are the project's to bring - see the `firmware`
    # declarations in waterbox.config and FindResource in the driver.
    ("IDR_HDDRVR_FW", "resource/Hddrvr.bin"),
    ("IDR_HDDRVR_V2_FW", "resource/Hddrvr-v2.bin"),
    ("IDR_HDC_SMARTPORT_FW", "resource/HDC-SmartPort.bin"),
]


def main():
    root, out = sys.argv[1], sys.argv[2]
    ids = {}
    with open(os.path.join(root, "resource/resource.h")) as f:
        for line in f:
            m = re.match(r"\s*#define\s+(ID\w+)\s+(\d+)", line)
            if m:
                ids[m.group(1)] = int(m.group(2))

    lines = [
        "/* generated by waterbox/gen-resources.py from the AppleWin checkout - do not edit */",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "struct ChimeraResource { uint16_t id; uint32_t size; const uint8_t *data; };",
        "",
    ]
    table = []
    for name, rel in RESOURCES:
        if name not in ids:
            sys.exit(f"{name} is not in resource.h")
        path = os.path.join(root, rel)
        with open(path, "rb") as f:
            data = f.read()
        var = "res_" + name.lower()
        body = ",".join(str(b) for b in data)
        lines.append(f"static const uint8_t {var}[{len(data)}] = {{{body}}};")
        table.append(f"\t{{ {ids[name]}, {len(data)}, {var} }}, /* {name}: {rel} */")
    lines.append("")
    lines.append("extern const ChimeraResource chimera_resources[];")
    lines.append("extern const size_t chimera_resource_count;")
    lines.append("const ChimeraResource chimera_resources[] = {")
    lines.extend(table)
    lines.append("};")
    lines.append(f"const size_t chimera_resource_count = {len(table)};")
    lines.append("")
    with open(out, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
